### ISSUE TITLE
修改js脚本建议。

### ISSUE THREAD

**Issue by Tfy2020** [lxmusics/lx-music-api-server-python#26]
脚本只有128k，但是修改为320k，flac和flac24bit时，自动修改为128k，导致无法下载高音质音乐。
有望建议大佬修改为删除脚本后运行.exe，发现无脚本.js时自动下载回默认配置。
并非是每一次启动都修改为默认配置，导致修改麻烦。（包括.json文件也是。）

**Comment by helloplhm-qwq** [comment]
脚本的配置是在config.json里配置的，你直接修改缓存的脚本，下一次缓存时就会覆盖掉

**Comment by helloplhm-qwq** [comment]
配置文件生成一次后就不会再覆盖，只有在更新了新的配置或者进行刷新登录的时候，项目才会主动写入新的配置文件，但是你原来的配置也并不会被删掉，并且除了刷新登录需要的配置文件，其他的配置文件并不会被修改
