### ISSUE TITLE
termux运行报错

### ISSUE THREAD

**Issue by xiatianPE** [lxmusics/lx-music-api-server-python#27]
![Screenshot_20240118_223148](https://github.com/lxmusics/lx-music-api-server-python/assets/121849812/7065726e-0007-47d5-baaa-1e9e87f00fa2)
帮忙解决一下

**Comment by xiatianPE** [comment]
> ![Screenshot_20240118_223148](https://private-user-images.githubusercontent.com/121849812/297774880-7065726e-0007-47d5-baaa-1e9e87f00fa2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODkwODUsIm5iZiI6MTcwNTU4ODc4NSwicGF0aCI6Ii8xMjE4NDk4MTIvMjk3Nzc0ODgwLTcwNjU3MjZlLTAwMDctNDdkNS1iYWFhLTFlOWU4N2YwMGZhMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNDM5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzA2NzU4MWQyZmU5YjRlZTY1NzdlNzRkMDA2NDA3NTZiMmYxYTM0ZjJhMGQ2OGI2YzMyZDMwYzJkNTM0NDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n7jGPJeZ_fjdtG_1GPZm4MemHHVpjfb3q1X89buU1Wg) 帮忙解决一下

**Comment by helloplhm-qwq** [comment]
网络问题
可以试下不用poetry
