### ISSUE TITLE
termux运行报错

### ISSUE THREAD

**Issue by xiatianPE** [lxmusics/lx-music-api-server-python#28]
![Screenshot_20240118_223148](https://github.com/lxmusics/lx-music-api-server-python/assets/121849812/ed0f8503-c450-4261-9b80-6e209a3df3fe)
帮忙解决一下

**Comment by helloplhm-qwq** [comment]
网络问题

**Comment by helloplhm-qwq** [comment]
不介意的话你可以直接pip在总环境装依赖，不要虚拟环境，这样可以配置index
