### ISSUE TITLE
无法用ipv6连接

### ISSUE THREAD

**Issue by Four-way-Xeon** [lxmusics/lx-music-api-server-python#29]
局域网内ipv4访问没问题，但是ipv6不通，使用telnet也无法在ipv6访问端口

**Comment by helloplhm-qwq** [comment]
把host改成::

记得给ipv6的访问host加白（如果你开了，不然是404）

之后再写v4v6双监听

刚刚考完期末

**Comment by esme518** [comment]
> 局域网内ipv4访问没问题，但是ipv6不通，使用telnet也无法在ipv6访问端口

也可以挂反代 来避免这些问题
