### ISSUE TITLE
希望能改进config文件的设置方式

### ISSUE THREAD

**Issue by esme518** [lxmusics/lx-music-api-server-python#32]
现在默认会把所有设置内容都写进config.json文件里
希望能像v2ray那样 在config.json只定义一些需要更改的内容 其他config.json没设置的内容都取默认值
这样在版本更新的时候也能避免旧config.json的兼容问题

**Comment by helloplhm-qwq** [comment]
现在就是这样啊

读取不存在的配置的时候使用默认值，并在config.json中写入

~~你把config.json改到只剩{}都不影响服务器启动~~

**Comment by esme518** [comment]
> 现在就是这样啊
> 
> 读取不存在的配置的时候使用默认值，并在config.json中写入
> 
> ~你把config.json改到只剩{}都不影响服务器启动~

我的意思是对于缺失的设置项目没必要在config.json中写入
这样可以把config.json保持尽可能简洁 
并且在更新中如果对某个设置项目名称改名了 也不会造成任何影响（比如说以前曾把proxy.http_addr改为proxy.http_value）

**Comment by helloplhm-qwq** [comment]
那样config更新了别人怎么修改

**Comment by esme518** [comment]
项目里有个config-sample.json就好

**Comment by helloplhm-qwq** [comment]
@esme518 你直接空启动一次就是默认配置
