### ISSUE TITLE
kuwo源配置kuwodes时报错

### ISSUE THREAD

**Issue by wang-zhix** [lxmusics/lx-music-api-server-python#37]
![image](https://github.com/lxmusics/lx-music-api-server-python/assets/59219784/77f88aa5-9faa-4d00-811a-d2c22a4ea8ac)
第一次循环之后，不应该重新在body中取值

应该这样修正
![image](https://github.com/lxmusics/lx-music-api-server-python/assets/59219784/cfcc17d6-3621-4c28-8d88-1e800b19685b)

同时接口返回值中的bitrate就是1，但下面判断了==1 将raise failed  不知是不是有意为之

**Comment by helloplhm-qwq** [comment]
据我所知bitrate=1的时候接口返回的是"您所播放的内容续开通会员后畅听"

不过你这样的修正不应该会引起重复调用吗，body调用get方法不会修改自身，在python中，在for循环中定义的变量离开for循环依旧可以使用

你光说个报错我咋知道为啥报错，请提供日志，谢谢你

**Comment by wang-zhix** [comment]
第一次循环p的值是'data'  从body中取body['data']     第二次循环p的值是'url' 应该从body['data']里取data['url']   肯定不能再从body中取url了呀
报错肯定报key不存在呀

**Comment by wang-zhix** [comment]
bitrate=1  的问题  我没测试完全   抱歉。 确实是返回了"您所播放的内容续开通会员后畅听"

**Comment by wang-zhix** [comment]
body = {
	'data': {
		'url' : 'http://**.mp3'
	}
}

for p in ['data', 'url']:
	body.get(p)


想要的应该是body['data']['url']

但这个代码却是 第一次循环body['data']    第二次循环body['url']     body肯定没有这个key呀
