### ISSUE TITLE
关于酷狗概念版签到操作

### ISSUE THREAD

**Issue by LoveU3th** [lxmusics/lx-music-api-server-python#41]
您好，我看到您代码中有部分关于概念版签到的代码，请问现在是否实现了呢？大概如何操作，感谢指导。

**Comment by helloplhm-qwq** [comment]
已经实现，你配置正确了就会每日自动执行

怎么配置自己研究

**Comment by LoveU3th** [comment]
我设置了config.json中的配置，但是仍然不能签到，提示err ，请教提示一下差在哪里，谢谢。配置如下：
"kg": {
      "desc": "酷狗音乐相关配置",
      "client": {
        "desc": "客户端请求配置，不懂请保持默认，修改请统一为字符串格式",
        "appid": "3116",
        "_appid-desc": "酷狗音乐的appid，官方安卓为1005，官方PC为1001",
        "signatureKey": "OIlwieks28dk2k092lksi2UIkp",
        "_signatureKey-desc": "客户端signature采用的key值，需要与appid对应",
        "clientver": "10518",
        "_clientver-desc": "客户端versioncode，pidversionsecret可能随此值而变化",
        "pidversionsecret": "57ae12eb6890223e355ccfcb74edf70d",
        "_pidversionsecret-desc": "获取URL时所用的key值计算验证值",
        "pid": "2"
      },
      "tracker": {
        "desc": "trackerapi请求配置，不懂请保持默认，修改请统一为字符串格式",
        "host": "https://gateway.kugou.com",
        "path": "/v5/url",
        "version": "v5",
        "x-router": {
          "desc": "当host为gateway.kugou.com时需要追加此头，为tracker类地址时则不需要",
          "enable": true,
          "value": "tracker.kugou.com"
        },
        "extra_params": {
        },
        "_extra_params-desc": "自定义添加的param，优先级大于默认，填写类型为普通的JSON数据，会自动转换为请求param"
      },
      "user": {
        "desc": "此处内容请统一抓包获取，需要vip账号来获取会员歌曲，如果没有请留为空值，mid必填，可以瞎填一段数字",
        "token": "9cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "userid": "21xxxxxxxxxxxx",
        "mid": "65xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "lite_sign_in": {
          "desc": "是否启用概念版自动签到，仅在appid=3116时运行",
          "enable": true,
          "interval": 86400,
          "mixsongmid": {
            "desc": "mix_songmid的获取方式, 默认auto, 可以改成一个数字手动",
            "value": "auto"

**Comment by LoveU3th** [comment]
> 已经实现，你配置正确了就会每日自动执行
> 
> 怎么配置自己研究

我设置了config.json中的配置，但是仍然不能签到，提示err ，请教提示一下差在哪里，谢谢。配置如下：
"kg": {
"desc": "酷狗音乐相关配置",
"client": {
"desc": "客户端请求配置，不懂请保持默认，修改请统一为字符串格式",
"appid": "3116",
"_appid-desc": "酷狗音乐的appid，官方安卓为1005，官方PC为1001",
"signatureKey": "OIlwieks28dk2k092lksi2UIkp",
"_signatureKey-desc": "客户端signature采用的key值，需要与appid对应",
"clientver": "10518",
"_clientver-desc": "客户端versioncode，pidversionsecret可能随此值而变化",
"pidversionsecret": "57ae12eb6890223e355ccfcb74edf70d",
"_pidversionsecret-desc": "获取URL时所用的key值计算验证值",
"pid": "2"
},
"tracker": {
"desc": "trackerapi请求配置，不懂请保持默认，修改请统一为字符串格式",
"host": "https://gateway.kugou.com/",
"path": "/v5/url",
"version": "v5",
"x-router": {
"desc": "当host为gateway.kugou.com时需要追加此头，为tracker类地址时则不需要",
"enable": true,
"value": "tracker.kugou.com"
},
"extra_params": {
},
"_extra_params-desc": "自定义添加的param，优先级大于默认，填写类型为普通的JSON数据，会自动转换为请求param"
},
"user": {
"desc": "此处内容请统一抓包获取，需要vip账号来获取会员歌曲，如果没有请留为空值，mid必填，可以瞎填一段数字",
"token": "9cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"userid": "21xxxxxxxxxxxx",
"mid": "65xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"lite_sign_in": {
"desc": "是否启用概念版自动签到，仅在appid=3116时运行",
"enable": true,
"interval": 86400,
"mixsongmid": {
"desc": "mix_songmid的获取方式, 默认auto, 可以改成一个数字手动",
"value": "auto"

**Comment by helloplhm-qwq** [comment]
@LoveU3th 签名key不对，自己抓

**Comment by LoveU3th** [comment]
> @LoveU3th 签名key不对，自己抓

从头学逆向了我，全靠GPT4

**Comment by ikun0014** [comment]
@LoveU3th 抓包没有，需要拆dex

**Comment by LoveU3th** [comment]
> @LoveU3th 抓包没有，需要拆dex

现学的jadx解包+frida hook逆向😂。没有走拆dex方式

**Comment by qssn70** [comment]
解决了吗
